---
title: "Lab 10- Cool and (sometimes) useful stuff"
author: "German Silva"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach libraries

library(tidyverse)
library(usethis)
library(beepr) # Installed
library(praise) # Installed
library(cowsay) # Installed
library(paletteer) # Installed
library(sf) # Installed
library(janitor)
```

## `beepr::beep()` to let you know when your code is done running

- Try it on it's own in the Console: `beep()`

- See the different options with `?beep()`

- Write a for loop + beep
  - rev(seq(1:99))

```{r, eval=FALSE}
for (i in rev(seq(1:999))){
  print(paste(i, "bottles of beer on the wall"))
}

beep(5)
```

## Praise is nice

```{r}
praise("${EXCLAMATION}! This code works ${adverb_manner}!")

praise("Holy ${creating}, Batman - this code works ${ADVERB_MANNER}")
```

## cowsay::say to have characters say something

```{r}
say("I love tacos!", by = "rms")
```

## usethis for everything

```{r}

```

